# Generated by Django 2.1.3 on 2018-11-30 22:52

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('sinopsis', models.CharField(max_length=200, verbose_name='Sinopsis')),
                ('poster', models.ImageField(blank=True, null=True, upload_to=api.utils.movie_image_upload_location, verbose_name='Poster')),
                ('resena', models.TextField(verbose_name='Reseña')),
                ('fecha_estreno', models.TextField(verbose_name='Fecha de estreno')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
                'ordering': ['titulo'],
            },
        ),
    ]
