# Generated by Django 2.1.3 on 2018-12-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pelicula_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(verbose_name='Fecha de estreno'),
        ),
    ]
