# Generated by Django 2.1.3 on 2018-12-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181202_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='poster',
            field=models.BinaryField(blank=True, null=True, verbose_name='Poster'),
        ),
    ]
