# Generated by Django 2.1.3 on 2018-12-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='fecha_estreno',
        ),
    ]
