# Generated by Django 2.1.3 on 2018-12-03 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_pelicula_fecha_estreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='fecha_estreno',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de estreno'),
        ),
    ]
